name: Continuous Integration

on: 
  push:
    branches: 
      - develop

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: node-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test --watchAll=false


